### ISSUE TITLE
Make correlations sensible

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-data-detective#11]
The calculated correlations can be 1.0 or -1.0 which must be due to insufficient data. Remove correlations with insufficient data.

**Comment by WillKoehrsen** [comment]
Any sensor correlated with itself will be 1.0 so that may be one issue. It is possible there could be -1.0 correlations if one sensor switches off at the same time another switches on.

**Comment by robmarkcole** [comment]
Those 1.0 correlations only came in after I added resampling at 1 second intervals. They have gone now I removed the resample.
