### ISSUE TITLE
Access InfluxDB?

### ISSUE THREAD

**Issue by voydz** [robmarkcole/HASS-data-detective#121]
Hey,

this is not really an issue, just a question I have. My current situation is described in the community forums here: https://community.home-assistant.io/t/hass-data-detective-access-influx-db-or-use-external-dbms/182534

I am curious if I might have overlooked something. Is there any possibility to access an influxdb with this?

best regards and thanks for your hard work with it,
Felix

**Comment by fabaff** [comment]
As far as I can tell not out-of-the-box.

It could work if you grab the data manually from the InfluxDB (e.g., https://github.com/influxdata/influxdb-client-python-pandas), create a dataframe and feed that to HASS-data-detective.

**Comment by robmarkcole** [comment]
influxdb is so popular it is worth supporting, probably just via a helper function

**Comment by robmarkcole** [comment]
not doing
