### ISSUE TITLE
Not available on PyPI

### ISSUE THREAD

**Issue by fabaff** [robmarkcole/HASS-data-detective#125]
The [latest release](https://github.com/robmarkcole/HASS-data-detective/releases/tag/v2.3) is not available on PyPI.

**Comment by fabaff** [comment]
The release on PyPI is still missing...any chance that it will be uploaded soon?

**Comment by robmarkcole** [comment]
thanks for bringing to my attention

**Comment by robmarkcole** [comment]
published 2.3 manually
