### ISSUE TITLE
Unable to retrieve Entities

### ISSUE THREAD

**Issue by nos86** [robmarkcole/HASS-data-detective#132]
Hello,
I don't know how to fix it the issue below. 
Can somehow help me?

```python
import detective.core
db=detective.core.HassDatabase(r"sqlite:///home-assistant_v2.db")
```
Successfully connected to database sqlite:///home-assistant_v2.db
Error with query: 
            SELECT entity_id
            FROM states
            GROUP BY entity_id
            
(sqlite3.OperationalError) no such table: states
[SQL: 
            SELECT entity_id
            FROM states
            GROUP BY entity_id
            ]
(Background on this error at: http://sqlalche.me/e/e3q8)

---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1243                     self.dialect.do_execute(
-> 1244                         cursor, statement, parameters, context
   1245                     )

/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    551     def do_execute(self, cursor, statement, parameters, context=None):
--> 552         cursor.execute(statement, parameters)
    553 

OperationalError: no such table: states

The above exception was the direct cause of the following exception:

OperationalError                          Traceback (most recent call last)
<ipython-input-26-e8693dc297d5> in <module>
----> 1 db=detective.core.HassDatabase(r"sqlite:///home-assistant_v2.db")

/usr/local/lib/python3.6/dist-packages/detective/core.py in __init__(self, url, fetch_entities)
     59             print("Successfully connected to database", stripped_db_url(url))
     60             if fetch_entities:
---> 61                 self.fetch_entities()
     62         except Exception as exc:
     63             if isinstance(exc, ImportError):

/usr/local/lib/python3.6/dist-packages/detective/core.py in fetch_entities(self)
     89             """
     90         )
---> 91         response = self.perform_query(query)
     92 
     93         # Parse the domains from the entities.

/usr/local/lib/python3.6/dist-packages/detective/core.py in perform_query(self, query, **params)
     75         """Perform a query, where query is a string."""
     76         try:
---> 77             return self.engine.execute(query, params)
     78         except:
     79             print("Error with query: {}".format(query))

/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py in execute(self, statement, *multiparams, **params)
   2167 
   2168         connection = self._contextual_connect(close_with_result=True)
-> 2169         return connection.execute(statement, *multiparams, **params)
   2170 
   2171     def scalar(self, statement, *multiparams, **params):

/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py in execute(self, object_, *multiparams, **params)
    986             raise exc.ObjectNotExecutableError(object_)
    987         else:
--> 988             return meth(self, multiparams, params)
    989 
    990     def _execute_function(self, func, multiparams, params):

/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py in _execute_on_connection(self, connection, multiparams, params)
    285     def _execute_on_connection(self, connection, multiparams, params):
    286         if self.supports_execution:
--> 287             return connection._execute_clauseelement(self, multiparams, params)
    288         else:
    289             raise exc.ObjectNotExecutableError(self)

/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py in _execute_clauseelement(self, elem, multiparams, params)
   1105             distilled_params,
   1106             compiled_sql,
-> 1107             distilled_params,
   1108         )
   1109         if self._has_events or self.engine._has_events:

/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1246         except BaseException as e:
   1247             self._handle_dbapi_exception(
-> 1248                 e, statement, parameters, cursor, context
   1249             )
   1250 

/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py in _handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   1464                 util.raise_from_cause(newraise, exc_info)
   1465             elif should_wrap:
-> 1466                 util.raise_from_cause(sqlalchemy_exception, exc_info)
   1467             else:
   1468                 util.reraise(*exc_info)

/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py in raise_from_cause(exception, exc_info)
    396     exc_type, exc_value, exc_tb = exc_info
    397     cause = exc_value if exc_value is not exception else None
--> 398     reraise(type(exception), exception, tb=exc_tb, cause=cause)
    399 
    400 

/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py in reraise(tp, value, tb, cause)
    150             value.__cause__ = cause
    151         if value.__traceback__ is not tb:
--> 152             raise value.with_traceback(tb)
    153         raise value
    154 

/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1242                 if not evt_handled:
   1243                     self.dialect.do_execute(
-> 1244                         cursor, statement, parameters, context
   1245                     )
   1246         except BaseException as e:

/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    550 
    551     def do_execute(self, cursor, statement, parameters, context=None):
--> 552         cursor.execute(statement, parameters)
    553 
    554     def do_execute_no_params(self, cursor, statement, context=None):

OperationalError: (sqlite3.OperationalError) no such table: states
[SQL: 
            SELECT entity_id
            FROM states
            GROUP BY entity_id
            ]
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by robmarkcole** [comment]
`(sqlite3.OperationalError) no such table: states` - might be the case, if sqlite doesnt find the db file it creates a blank one. Check the path to the file, I remember something annoying about the number of `/` used

**Comment by robmarkcole** [comment]
no response, closing
