### ISSUE TITLE
Problem with View States section in Getting Started : 'HassDatabase' object has no attribute 'fetch_all_data'

### ISSUE THREAD

**Issue by dmshimself** [robmarkcole/HASS-data-detective#137]
I have a problem using the Home Assistant addon referred to here: [https://github.com/hassio-addons/addon-jupyterlab/issues/241](url) which I was asked to report here.

When the home-assistant/GETTING_STARTED notebook is run, the first sections run fine, but the section:

db.fetch_all_data()

returns an error:

AttributeError  Traceback (most recent call last) <timed eval> in <module>
AttributeError: 'HassDatabase' object has no attribute 'fetch_all_data'

**Comment by robmarkcole** [comment]
Can you fix the link to the issue?

It should be calling `fetch_all_sensor_data`

**Comment by dmshimself** [comment]
Whoops:

https://github.com/hassio-addons/addon-jupyterlab/issues/241

I manually changed the fetch_all_data to fetch_all_sensor_data and that part went through very nicely.  Many thanks Rob.

Would you have any comments on the next section which produces an assertion error?

assert 'binary_sensor' and 'sensor' in db.domains
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-ed971f338261> in <module>
----> 1 assert 'binary_sensor' and 'sensor' in db.domains

AttributeError: 'HassDatabase' object has no attribute 'domains'

**Comment by robmarkcole** [comment]
My guess is you have updated the detective dependency, but are still using a version of the getting started notebook from and old verison of detective. Please use `Getting started with detective.ipynb` from this repo

**Comment by dmshimself** [comment]
Thanks Rob - I'll pass that on to the developer of the Home Assistant Add on.

**Comment by robmarkcole** [comment]
Created https://github.com/home-assistant/home-assistant-notebooks/issues/20

**Comment by robmarkcole** [comment]
PR merged, closing
