### ISSUE TITLE
OperationalError: no such column: domain

### ISSUE THREAD

**Issue by etmmafl** [robmarkcole/HASS-data-detective#143]
In [corepy](https://github.com/robmarkcole/HASS-data-detective/blob/f861f7064c1f69ee0c167d858cca70e7e22fc985/detective/core.py) there is a function [db.fetch_all_data_of] that generates an error [OperationalError: no such column: domain] because it is querying the following:
```
SELECT domain, entity_id, state, last_changed, attributes
FROM states
```
However, [domain] is not an column in this table. It does not exist.

**Comment by robmarkcole** [comment]
duplicates https://github.com/robmarkcole/HASS-data-detective/issues/142
