### ISSUE TITLE
Raspbian failed

### ISSUE THREAD

**Issue by wspeth** [robmarkcole/HASS-data-detective#149]
tried the docker command on raspberry pi .. and failed_
latest: Pulling from jupyter/scipy-notebook
docker: no matching manifest for linux/arm/v7 in the manifest list entries.

**Comment by robmarkcole** [comment]
Please see https://github.com/robmarkcole/HASS-data-detective/commit/1203c011ab1ea9e1acf1859910299945f6f03e76
