### ISSUE TITLE
ValueError: Array must be all same time zone

### ISSUE THREAD

**Issue by rtclauss** [robmarkcole/HASS-data-detective#26]
Hi, I'm starting to play around with your example [hass-detective](https://kyso.io/robmarkcole/hass-data-detective) notebook in my own environment.  I've pulled the master branch and made a few changes to your notebook code to pick up what's in master.  When I try to use the NumericalSensors class I get a `ValueError` exception.
```python
sensors_num = detective.NumericalSensors(parser.master_df)
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/pandas/core/tools/datetimes.py in _convert_listlike(arg, box, format, name, tz)
    302             try:
--> 303                 values, tz = tslib.datetime_to_datetime64(arg)
    304                 return DatetimeIndex._simple_new(values, name=name, tz=tz)

pandas/_libs/tslib.pyx in pandas._libs.tslib.datetime_to_datetime64()

ValueError: Array must be all same time zone

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-5-8918ff9e5054> in <module>()
----> 1 sensors_num = detective.NumericalSensors(parser.master_df)

~/work/HASS-data-detective/detective/core.py in __init__(self, master_df)
    183             index='last_changed', columns='entity', values='state')
    184 
--> 185         sensors_num_df.index = pd.to_datetime(sensors_num_df.index)
    186         sensors_num_df.index = sensors_num_df.index.tz_localize(None)
```

We hit Daylight Savings time a few weeks ago so I there's a mix of UTC-5 and UTC-6 in my database. Not sure what the right solution is...converting to unix time or, how I managed to fix the problem, is to modify NumericalSensors's `__init__` to read:
```python
        sensors_num_df.index = pd.to_datetime(sensors_num_df.index, utc=True)
        sensors_num_df.index = sensors_num_df.index.tz_localize(None)
```

**Comment by robmarkcole** [comment]
Hi @rtclauss thanks for the issue :-)
Could you try editing line 185 to be:
`sensors_num_df.index = pd.to_datetime(sensors_num_df.index, errors='ignore', utc=True`
Cheers

**Comment by rtclauss** [comment]
Thanks @robmarkcole.  I made the change in NumericalSensor and the code works as expected. There's another instance of the tz parsing code in BinarySensors and your code fix works there, too.
