### ISSUE TITLE
Make timestamps consistent

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-data-detective#3]
The formatting of timestamps varies with the different plot functions. Need to select a format and make it universal.

**Comment by WillKoehrsen** [comment]
That's tough because the sensors record at different intervals. We might need to establish a standard for each separate sensor. Pandas datetimes are relatively easy to deal with, but we need to decide if they should be timezone aware or not. I would imagine we do need timezones for most sensors.

**Comment by robmarkcole** [comment]
We could allow the user to set the timezone, however it is set in the home-assistant config so ultimately we want a function to parse their config.

**Comment by robmarkcole** [comment]
timestamps are now handled
