### ISSUE TITLE
Drop SQL queries and use sqlalchemy exclusively

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-data-detective#53]
Sqlalchemy takes care of issues like handling datetime objects, so we could use if for queries rather than SQL which may return strings rather than python objects we care about

**Comment by robmarkcole** [comment]
Too much overhead

**Comment by bramkragten** [comment]
If we expect a datetime just check if it returns a string and convert it to a datetime? If this is only a problem for datetime...
