### ISSUE TITLE
Warn about `mysql://`

### ISSUE THREAD

**Issue by balloob** [robmarkcole/HASS-data-detective#61]
We want users to use `mysql+pymysql://` because SQLAlchemy defaults with `mysql` to a package that does not support Python 3.

We should print a warning if we detect this that people should manually configure it. Maybe if we catch an `ImportError` ?

**Comment by robmarkcole** [comment]
Determining the correct url can be quite confusing. Perhaps we just init with db type, password etc, and generate the url.?

**Comment by balloob** [comment]
Then we're reimplementing a part of SQLAlchemy. That doesn't seem right.

I think a proper warning when `ImportError` happens should be a good start

**Comment by robmarkcole** [comment]
OK lets do that then. I have time to work on it next week. but busy this week
