### ISSUE TITLE
Investigate Dask

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-data-detective#73]
For databases/dataframes that won't fit in memory, investigate Dask

http://docs.dask.org/en/latest/dataframe.html

**Comment by SupahNoob** [comment]
Instead of using Dask, I would highly encourage you to socialize the concept of filtering the dataset to what is most desired. Even a simple date/entity filter will go a long ways.

Dask may fix the symptom, but not the underlying problem.

**Comment by robmarkcole** [comment]
HI @SupahNoob yes I'm inclined to agree, although encouraging the community to follow a best practice usually involves repeating the same comments over and over in the forums :-)
I added a feature to export only useful columns of numeric data, and I see the purpose of detective as enabling users to extract a decent pandas dataframe from their HA data, so any additional processing of data should be beyond the scope of this package

**Comment by robmarkcole** [comment]
out of scope
