### ISSUE TITLE
Install in HASS virtual env?

### ISSUE THREAD

**Issue by jonwaland** [robmarkcole/HASS-data-detective#84]
Not knowing the dependencies and interactions, should this be installed in the same virtual env that HASS has been installed in, or a new/seperate one, or just global?

Given it gets installed as a HASS.IO addon, I'm tending the former.... #

**Comment by robmarkcole** [comment]
Hi, if you are using the addon Detective is already installed for you.
On your own laptop, global should be fine, unless you are doing development.
Cheers

**Comment by jonwaland** [comment]
I'm not running HASS.IO and so can't install the addion as an addon.

I'm running hass in a python virtual environment under ubuntu.

**Comment by robmarkcole** [comment]
I recommend you create a separate env for detective and use the db url rather that auto discover from your config

**Comment by jonwaland** [comment]
cool. thanks.
