### ISSUE TITLE
ValueError: Secrets file /config/includes/secrets.yaml not found

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-data-detective#85]
From the forum: When running the cells within the ‘GETTING STARTED’ workbook I recieve an error: ValueError: Secrets file /config/includes/secrets.yaml not found.
My ‘secrets.yaml’ file is directly within ‘/config/’ directory

**Comment by robmarkcole** [comment]
Probably a docker thing. Close unless someone reports again

**Comment by basnijholt** [comment]
I get this exact same error.

**Comment by basnijholt** [comment]
@robmarkcole, could you reopen this issue?

I describe how to reproduce this error in the test in #119.
