### ISSUE TITLE
SyntaxError when trying to Initialise HA Database

### ISSUE THREAD

**Issue by CM000n** [robmarkcole/HASS-data-detective#92]
Since I use Zeppelin at work and I'm a bit more familiar with it than with Jupyter, I tried to initialize and use the HASS-data-detective with it.
Unfortunately every time I try to initialize my Home Assistant database I get an error message about a SyntaxError.
I use the HASS-data-detective inside the standard Zeppelin 0.8 Docker container and installed it before via "pip install HASS-data-detective".

![syntaxerrordetective](https://user-images.githubusercontent.com/7945681/50678238-09adb680-0ffe-11e9-8900-a7e9709ce0c6.PNG)

**Comment by robmarkcole** [comment]
Syntax error suggests your python version isn't compatible

**Comment by CM000n** [comment]
Oh, shame on me. You're absolutely right! 
As Version for the standard Python interpreter, Python 2.7 is currently used inside the Zeppelin Docker Container. After I created an interpreter for Python3, it works as intended. :-)

![detective](https://user-images.githubusercontent.com/7945681/50691837-41ceec80-1032-11e9-9366-ff8b78a1e80f.PNG)
