### ISSUE TITLE
Adding a new HA sensor makes all existing data unavailable.

### ISSUE THREAD

**Issue by davidedmundson** [robmarkcole/HASS-data-detective#94]
Recently hass detective stopped showing all my historical data. 
I figured out why, but I don't have a solution.

After pivoting the data we fill the gaps, then remove all rows with any invalid value.

In the NumericalSensors constructor
        sensors_num_df = sensors_num_df.fillna(method="ffill")

At this point a newly added sensor appears in the table as Nan, NaN, NaN..., firstValidValue, firstValidValue,  only filling gaps forwards. 

When we get to:

        sensors_num_df = sensors_num_df.dropna()  # Drop any remaining nan.

We drop all the rows before this new sensor was added.

**Comment by robmarkcole** [comment]
@davidedmundson sorry I just noticed this issue, this is indeed an issue. However I am unsure of a good solution, but in the meantime you could backfill the values for that sensor

**Comment by davidedmundson** [comment]
I don't think there is any perfect solution inside HA-detective. Back-filling in HA introduces "lies" in the data and we want that as pure as possible.

Personally I dropped the line from my ha-detective locally and moved the responsibility of calling dropna before plotting to user code.

**Comment by robmarkcole** [comment]
this should not be an issue in the v2 branch
