### ISSUE TITLE
error running Getting started - with  hassio addon

### ISSUE THREAD

**Issue by gnkarn** [robmarkcole/HASS-data-detective#95]
im using hassio addon, not the detective , as i wasnt sure were to post , here I am .

When running the Getting started notebook : 
`FileNotFoundError:` [Errno 2] No such file or directory: '/config/automation/panels.yaml'

the error is understandable, because i do not have a panels under automation, i dont understand why is looking for that file there.

in order no to be tedious , i would like to know if the examples are not suffering from not being updated , as i was not able to run a single one of them without errors , 
thank you .!

**Comment by robmarkcole** [comment]
HI @gnkarn 
I just ran the addon with HA 91.4 and cannot reproduce your issue. I suggest we wait and see if anyone else reports similar before digging deeply, as it may be particular to your config setup (@balloob wrote this part of the package). In the meantime you can manually point to the db following:

```python
from detective.core import HassDatabase
db = detective.HassDatabase('sqlite:////' + 'config/home-assistant_v2.db')
```

**Comment by robmarkcole** [comment]
stale
